name: games_info
description: App about games info.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_lints: ^2.0.0
  flutter_dotenv: ^5.0.2
  flutter_bloc: ^8.0.0
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  

flutter:
  uses-material-design: true